{
 "title": "Generator Overview",
 "description": "Generator metrics",
 "tags": [ "generator" ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "10s",
 "panels": [
  {
   "title": "Last Run (Age)",
   "type": "stat",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "time() - last_run_timestamp_seconds",
     "legendFormat": "{{type}}"
    }
   ]
  },
  {
   "title": "Last Run Duration",
   "type": "stat",
   "gridPos": { "h": 5, "w": 8, "x": 8, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    { "expr": "generate_duration_seconds", "legendFormat": "{{type}}" }
   ]
  },
  {
   "title": "Items Generated (Last Run)",
   "type": "stat",
   "gridPos": { "h": 5, "w": 8, "x": 16, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    { "expr": "generated_items_total", "legendFormat": "{{type}}" }
   ]
  },
  {
   "title": "Generated Items Over Time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    { "expr": "generated_items_total", "legendFormat": "{{type}}" }
   ]
  }
 ]
}